#!/bin/bash

#CIT 470-0001 Project 3
#Darci Guriel
#Group 3: Austin Elkins, Alyssa Herrman, Lisa Stock

# Script to configure monit and syslog on clients
# Takes ip address of server as argument
# TO DO - bash check for argument
#       - syslog config

# Installations
yum install epel-release -y
yum install monit -y

# MONIT CONFIG
# Global - leaving set configs inline
sed -i '/^set log syslog/a set logfile syslog facility log_daemon' /etc/monitrc
sed -i 's/# set mailserver mail.bar.baz,/  set mailserver 127.0.0.1/' /etc/monitrc 
sed -i 's/# set alert sysadm@foo.bar/ set alert lmstock23@gmail.com /' /etc/monitrc 
sed -i '/^ set alert lmstock23@gmail.com /a  set alert  root@localhost' /etc/monitrc

# WEB MONIT - ON FOR TESTING - LIKELY REMOVE FOR SUBMISSION 
sed -i 's/set httpd port 2812 and/set httpd port 2812   /' /etc/monitrc
sed -i 's/    allow localhost/    allow 0.0.0.0\/0.0.0.0/' /etc/monitrc

# Services - Appended to end of /etc/monitrc

echo "###############################################################################" >> /etc/monitrc
echo "## Group 3 Project 3 Configs" >> /etc/monitrc
echo "###############################################################################" >> /etc/monitrc
echo "   check process syslogd with pidfile /var/run/syslogd.pid" >> /etc/monitrc
echo "     start program  "/usr/bin/systemctl start rsyslog"" >> /etc/monitrc                      # <---- TEST FOR SYNTAX
echo "     stop program  "/usr/bin/systemctl stop rsyslog"" >> /etc/monitrc
echo "     if 5 restarts within 5 cycles then timeout" >> /etc/monitrc
echo "      " >> /etc/monitrc
echo "   check process sshd with pidfile /var/run/sshd.pid" >> /etc/monitrc
echo "     start program  "/usr/bin/systemctl start sshd"" >> /etc/monitrc                     # <---- TEST FOR SYNTAX
echo "     stop program  "/usr/bin/systemctl stop sshd"" >> /etc/monitrc
echo "     if failed port 22 protocol ssh then restart" >> /etc/monitrc
echo " " >> /etc/monitrc
echo "   check system localhost" >> /etc/monitrc
echo "     if loadavg (5min) > 3 for 4 cycles then alert" >> /etc/monitrc
echo "     if loadavg (15min) > 1 for 4 cycles then alert" >> /etc/monitrc
echo "     if memory usage > 80% for 4 cycles then alert" >> /etc/monitrc
echo "     if swap usage > 20% for 4 cycles then alert" >> /etc/monitrc
echo "     if cpu usage (user) > 80% for 4 cycles then alert" >> /etc/monitrc
echo "     if cpu usage (system) > 20% for 4 cycles then alert" >> /etc/monitrc
echo "     if cpu usage (wait) > 20% for 4 cycles then alert" >> /etc/monitrc
echo "    " >> /etc/monitrc
echo "  check filesystem rootfs with path /dev/sda1" >> /etc/monitrc
echo "    if space usage > 80% for 5 times within 15 cycles then alert" >> /etc/monitrc
echo "     " >> /etc/monitrc
echo "   check filesystem varfs with path /dev/sda2" >> /etc/monitrc
echo "     if space usage > 80% for 5 times within 15 cycles then alert" >> /etc/monitrc
echo "    " >> /etc/monitrc
echo "   check filesystem homefs with path /dev/sda4" >> /etc/monitrc
echo "     if space usage > 80% for 5 times within 15 cycles then alert  " >> /etc/monitrc
echo "     " >> /etc/monitrc
echo "  check host stockl1Server.hh.nku.edu with address $1" >> /etc/monitrc
echo "    if failed ping then alert" >> /etc/monitrc
echo "    if failed port 111 timeout 15 seconds then alert" >> /etc/monitrc
echo "    if failed port 20048 timeout 15 seconds then alert" >> /etc/monitrc
echo "    if failed port 2049 timeout 15 seconds then alert" >> /etc/monitrc
echo "    if failed port 389 timeout 15 seconds then alert" >> /etc/monitrc
echo "    if failed port 636 timeout 15 seconds then alert" >> /etc/monitrc

systemctl start monit
# monit reload

# Opens Monit web console ports
firewall-cmd --zone=public --add-port=2812/udp --permanent
firewall-cmd --zone=public --add-port=2812/tcp --permanent
firewall-cmd --reload


# SYSLOG CONFIG
sed -i 's/#$ModLoad imudp/$ModLoad imudp/' /etc/rsyslog.conf
sed -i 's/#$UDPServerRun 514/$UDPServerRun 514/' /etc/rsyslog.conf
sed -i 's/#$ModLoad imtcp/$ModLoad imtcp/' /etc/rsyslog.conf
sed -i 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/' /etc/rsyslog.conf
