#!/bin/bash

#CIT 470-0001 Project 3
#Darci Guriel
#Group 3: Austin Elkins, Alyssa Herrman, Lisa Stock

# Script to test monitoring solution



# line that kills syslog service
cat /var/run/syslogd.pid | xargs kill
