#!/bin/bash

#CIT 470-0001 Project 3
#Darci Guriel
#Group 3: Austin Elkins, Alyssa Herrman, Lisa Stock

# Script to test monitoring solution

  # 2.5 min
  # kill a service
  # sleep 30
  # verify alert ?  like echo monit summary ?
  # repeat for services
  
  # 3 min
  # close firewall port
  # sleep 30
  # verify alert
  # open port
  # repeat for ports
  
  # mayb 3 min
  # fill disk
  # verify alert
  # stress cpu
  # verify alert
  # stress ram
  # verify alert


# line that kills syslog service
cat /var/run/syslogd.pid | xargs kill

# line that kills sshd service
cat /var/run/sshd.pid | xargs kill

# line from perm mon lab that fills up disk - may need more zeros for 8G /home
dd if=/dev/zero of=/home/zero bs=512 count=10000000

